spring.application.name=verify-service
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
server.servlet.context-path=/v1/verify
spring.datasource.url=jdbc:postgresql://localhost:5432/inji_verify?currentSchema=verify
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8081
mosip.openid.htmltemplate=credential-template.html

# The below configuration is set for VP request status long polling timeout set with env INJI_VP_REQUEST_LONG_POLLING_TIMEOUT, if not set the default value >
inji.vp-request.long-polling-timeout=${INJI_VP_REQUEST_LONG_POLLING_TIMEOUT:55000}