spring.application.name=verify-service
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
server.servlet.context-path=/v1/verify
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.profiles.active=local
mosip.openid.htmlTemplate=credential-template.html

# The below configuration is set for VP request status long polling timeout set with env INJI_VP_REQUEST_LONG_POLLING_TIMEOUT, if not set the default value >
inji.vp-request.long-polling-timeout=${INJI_VP_REQUEST_LONG_POLLING_TIMEOUT:55000}
## Properties relayted to bank of brazil
govbr.bb.token.base.url=https://webhook-mgi.mtls.api.hm.bb.com.br
govbr.bb.token.uri=/oauth/token
govbr.bb.token.grant.type=client_credentials
govbr.bb.token.scope=webhook-mgi.requisicao
govbr.bb.token.auth=${GOVBR_BB_TOKEN_AUTH}
govbr.bb.api.key=gw-dev-app-key
govbr.bb.client.cert-path=/certs/client.crt
govbr.bb.client.key-path=/certs/client.key
govbr.bb.ca.cert-path=/certs/ca.crt
govbr.bb.webhook.uri.path=/v1/response/files

mtls.client.keystore-path=${KEYSTORE_PATH}
mtls.client.keystore-password=${KEYSTORE_PASSWORD}
mtls.client.truststore-path=${TRUSTSTORE_PATH}
mtls.client.truststore-password=${TRUSTSTORE_PASSWORD}