commonLabels:
  app.kubernetes.io/component: inji

containerSecurityContext:
  enabled: false
  runAsUser: inji
  runAsNonRoot: true

modules:
  injiverify:
    enabled: true
    image:
      repository: injistack/apitest-inji-verify
      tag: 0.17.0
      pullPolicy: Always

extraEnvVarsCM:
  - inji-stack-config
  - s3
  - keycloak-host
  - db
  - apitestrig
  - config-server-share

apitestrig:
  volumes:
    configmaps:
      scripts:
        defaultMode: 0777
        volumeMounts:
          mountPath: '/home/inji/scripts/'